---
title: "test"
output: html_document
date: "2023-04-20"
---

```{r, echo = FALSE}

library(dplyr)
library(ggplot2)
library(maps)
library(plotly)
library(readxl)
library(ggrepel)
library(lubridate)
library(shiny)
library(stringr)
library(tidyverse)
library(scales)

excel_data <- readxl::read_excel("gun_violence_curated.xlsx")

df <- excel_data %>%
  select(incident_date, state, n_injured) %>% 
  group_by(year = floor_date(incident_date, unit = 'year'), state) %>%
  summarise(total_incidents = n(),
            injured = sum(n_injured),
            .groups = 'drop') %>%
  mutate(year = year(year)) %>% 
  arrange(desc(total_incidents))
```

# Define server logic to read selected file ----

# Create Shiny app ----

```{r, echo = FALSE}
shinyApp(
  # Define UI for data upload app ----
ui = fluidPage(
  
  # App title ----
  titlePanel(""),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      selectizeInput(inputId = 'stateInput',
                     choices = sort(unique(df$state)),
                     label = 'States',
                     multiple = T,
                     options = list(maxItems = 5,
                                    placeholder = 'Select a name'),
                     selected = 'California'),
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Data file ----
      plotlyOutput(outputId = 'plot')
      
    )
    
  )
),

server = function(input, output) {
  
  output$plot <- renderPlotly({
    
    filtered_data <- df %>% 
      filter(state %in% input$stateInput)
    
    ggplot_plot <- ggplot(data = filtered_data,
           mapping = aes(x = year,
                        y = total_incidents,
                        colour = state))+
      geom_line()+
      geom_point(aes(size = injured), alpha = 0.8)+
      labs(title = 'Total incidents of gun violence (2013-2018)',
           x = 'Year',
           y = 'Number of Incidents',
           colour = 'States')+
      scale_y_continuous(labels=scales::comma)+
      theme_bw()
      
    
    ggplotly(ggplot_plot)
    
  })
  
}

)

```
